### ISSUE TITLE
使用data下的数据，训练了下，recall、acc和f1都提不上去啊，loss在3基本不变了呢

### ISSUE THREAD

**Issue by AnddyWang** [yangxudong/soft_mask_bert#1]
![image](https://user-images.githubusercontent.com/19400072/98455889-6279a780-21b1-11eb-8ae1-3b6284ab910e.png)

**Comment by SonofGod-lucky** [comment]
报错：‘nonetype’ object has no attribute '_inbound_nodes' ， 请问楼主怎么解决

**Comment by wangbq18** [comment]
> 报错：‘nonetype’ object has no attribute '_inbound_nodes' ， 请问楼主怎么解决

我也是同样的问题，预测是环境不一致导致，老哥解决了吗？

**Comment by qilinzi** [comment]
请问楼主解决了吗，我和您遇到的问题是一样的

**Comment by AnddyWang** [comment]
> 请问楼主解决了吗，我和您遇到的问题是一样的

没有，弃了这个了。。。
